---

# Packages

- name: Install packages from the official repo
  apt:
    name:
      - htop
      - vim
      - cryptsetup
      - bzip2
      - fish
      - whois
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - hdparm
    state: present
    update_cache: yes
  environment:
    RUNLEVEL: 1
    

# Users and groups

- name: Create shared group
  group:
      name: "{{ general.shared_group }}"
      state: present

- name: Create or update users
  user:
      name: "{{ item.name }}"
      home: "/mnt/{{ drives[general.homes_drive].name }}/homes/{{ item.name }}"
      create_home: yes
      groups:
        - "{{ general.shared_group }}"
      state: present # not required. choices: absent;present. Whether the account should exist or not, taking action if the state is different from what is stated.
  with_items: "{{ users }}"

# Raspirack

- name: Raspirack service file
  copy:
      dest: /etc/systemd/system/raspirack.service
      src: raspirack.service

- name: Raspirack service
  service:
      name: raspirack
      enabled: true
      state: restarted

# Docker

# Doesn't work with the new Raspbian yet
# - name: Docker CE repo key
#   apt_key:
#       url: https://download.docker.com/linux/debian/gpg
#       state: present

# - name: Docker CE repo
#   apt_repository:
#       repo: "deb [arch=armhf] https://download.docker.com/linux/debian    buster    stable"
#       state: present

# - name: Update apt cache
#   apt: update_cache=yes

# - name: Install docker CE
#   apt:
#       name: "{{ item }}"
#   loop:
#     - docker-ce
#     - docker-ce-cli
#     - containerd.io



# Prevents HDD from spin-down for drives that forces it regardless configuration via hdparm.

- name: HDD keep alive file
  lineinfile:
    path: /mnt/{{ item.name }}/.keepalive
    line: "Keep-alive file that is read every few minutes to prevent HDD from sleeping."
  loop: "{{ drives }}"

- name: HDD keep alive cron  
  cron:
    job: /mnt/{{ item.name }}/.keepalive
    name: "hdd keepalive of {{ item.name }}"
    hour: "*"
    minute: "*"
    day: "*"
    month: "*"
    weekday: "*"
  loop: "{{ drives }}"
