---

- name: APM service
  copy:
      dest: /etc/systemd/system/apm@.service
      src: apm@.service

- name: Setup APM service
  systemd:
      no_block: yes
      name: apm@{{ item.uuid }} # not required. Name of the service. When using in a chroot environment you always need to specify the full name i.e. (crond.service).
      enabled: yes
      daemon_reload: yes # not required. run daemon-reload before doing any other operations, to make sure systemd has read any changes.
      state: started # not required. choices: reloaded;restarted;started;stopped. C(started)/C(stopped) are idempotent actions that will not run commands unless necessary. C(restarted) will always bounce the service. C(reloaded) will always reload.
  with_items: "{{ drives }}"

- name: Setup up encrypted drives
  shell: echo "{{ ENCRYPTION_PASSWORD }}" | cryptsetup open /dev/disk/by-uuid/{{ item.uuid }} {{ item.name }}
  tags:
    - never
    - mount
  with_items: "{{ drives }}"
  when: item.encrypted

- name: Prepare mount points
  file:
      path: /mnt/{{ item.name }}
      state: directory
      mode: 755
      owner: root
      group: "{{ general.shared_group }}"
  tags:
    - never
    - mount
  with_items: "{{ drives }}"

- name: Mount drives
  command: mount -o defaults /dev/mapper/{{ item.name }} /mnt/{{ item.name }}
  tags:
    - never
    - mount
  with_items: "{{ drives }}"

- name: Umount drivers
  command: umount /dev/mapper/{{ item.name }}
  tags:
    - never
    - umount
  with_items: "{{ drives }}"

- name: Close encrypted drives
  command: cryptsetup close /dev/mapper/{{ item.name }}
  tags:
    - never
    - umount
  with_items: "{{ drives }}"
  when: item.encrypted
